### ISSUE TITLE
make install lacks DESTDIR support for findlib

### ISSUE THREAD

**Issue by olafhering** [ocaml/Zarith#63] opened 2019-09-25 16:31 UTC
There is appearantly no concept of DESTDIR. One can use `--installdir` to concat DESTDIR+$prefix, but ocamlfind does not cope with it:

````
[    4s] + make install DESTDIR=/home/abuild/rpmbuild/BUILDROOT/ocaml-zarith-1.9.1-190925162731.0.x86_64
[    4s] ocamlfind install -destdir "/home/abuild/rpmbuild/BUILDROOT/ocaml-zarith-1.9.1-190925162731.0.x86_64/usr/lib64/ocaml" zarith META zarith.h zarith.cma libzarith.a z.mli q.mli big_int_Z.mli z.cmi q.cmi big_int_Z.cmi zarith_top.cma zarith.a zarith.cmxa z.cmx q.cmx big_int_Z.cmx zarith.cmxs z.cmti q.cmti big_int_Z.cmti -optional dllzarith.so
[    4s] ocamlfind: Bad configuration: Cannot mkdir /home/abuild/rpmbuild/BUILDROOT/ocaml-zarith-1.9.1-190925162731.0.x86_64/usr/lib64/ocaml/zarith because a path component does not exist or is not a directory
````

Apparently the `install -d` command must also be used the `findlib` case.

**Comment by olafhering** [comment] 2019-09-25 16:35
There is more hackery required for findlib, but that might not be a concern for zarith itself:
````
export OCAMLFIND_DESTDIR=%{buildroot}`ocamlc -where`
export OCAMLFIND_LDCONF=/dev/null
mkdir -vp $OCAMLFIND_DESTDIR
%make_install
```

**Comment by xavierleroy** [comment] 2019-09-26 07:39
I agree this issue is not specific to Zarith, but an instance of a more general question: how to make `ocamlfind install` play nice with installation in a temporary staging directory?  

I'm sure there are examples among Fedora's packages for OCaml libraries, but a quick Web search turned nothing.  Perhaps @rwmjones could point you to an example.

**Comment by olafhering** [comment] 2019-09-26 07:46
Well, so far I handled this with the `%ocaml_oasis_findlib_install` macro, which essentially does the steps above. I just added zarith to our list of pkgs in [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml) because other packages require it. 

Instead of rolling my own `_oasis` file I deciced to reuse the upstream version of make/make install.

**Comment by xavierleroy** [comment] 2019-09-26 08:55
I support your decision to not using Oasis-dependent stuff.  Oasis for OCaml projects is on its way out and I would not use it today.

It seems the problem is fixed, so I'm closing this PR.  Reopen if nedded.

**Closed by xavierleroy** 2019-09-26 08:55 UTC

**Comment by rwmjones** [comment] 2019-10-02 10:14
FWIW here is how we install zarith into a staging directory:

https://src.fedoraproject.org/rpms/ocaml-zarith/blob/master/f/ocaml-zarith.spec#_79

and here is the general technique for findlib packages:

https://src.fedoraproject.org/rpms/ocaml-xml-light/blob/master/f/ocaml-xml-light.spec#_82
